name: LokaVotA
main: com.cryptite.pvp.LokaVotA
version: 1.0
author: Cryptite
depend: [VanishNoPacket]
commands:
  pvp:
     description: pvp?
     usage: /pvp
  leave:
     description: Leave the match
     usage: /leave
  p:
     description: Public chat
     usage: /p
  t:
     description: Town chat
     usage: /t
  a:
     description: Alliance chat
     usage: /a
  talents:
     description: View your talents
     usage: /talents
  inspect:
     description: Inspect talents
     usage: /inspect
  shutdown:
       description: Sends all players back to Loka before restart
       usage: /shutdown